import { AppTheme } from '../types';

const sceneImages = {
  rajasthan: require('../../assets/scenes/rajasthan.png'),
  kerala: require('../../assets/scenes/kerala.jpg'),
  assam: require('../../assets/scenes/assam.jpg'),
  himalaya: require('../../assets/scenes/himalaya.jpg'),
  andaman: require('../../assets/scenes/andaman.jpg'),
};

export const THEMES: AppTheme[] = [
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    subtitle: 'Golden evening dunes',
    feeling: 'Warm silence beyond the horizon',
    backgroundImage: sceneImages.rajasthan,
    backgroundGradient: ['#120905D9', '#2C160AD1', '#5C3518BF', '#170B05F2'],
    lightGradient: ['#F8D49B66', '#C8762E38', '#1A0904CC'],
    accentColor: '#E6A45B',
    secondaryAccentColor: '#B96535',
    buttonStyle: { backgroundColor: '#E6A45B1A', borderColor: '#E6A45B55', textColor: '#FFF3E4' },
    particlePreset: 'sand',
    particleDensity: 16,
    ambientPreset: 'desertWind',
    ambientSound: 'Soft desert wind',
    animationStyle: 'heatShimmer',
    voicePreset: 'warm_evening',
    textColor: '#FFF4E8',
    subtextColor: '#D6B188',
  },
  {
    id: 'kerala',
    name: 'Kerala',
    subtitle: 'Morning rainforest',
    feeling: 'Water, birds, and green quiet',
    backgroundImage: sceneImages.kerala,
    backgroundGradient: ['#031008E8', '#082214D4', '#124328B8', '#031009F2'],
    lightGradient: ['#BDECCB55', '#1F8F5533', '#031008D9'],
    accentColor: '#60D892',
    secondaryAccentColor: '#2F8F65',
    buttonStyle: { backgroundColor: '#60D89217', borderColor: '#60D8924D', textColor: '#E9FFF2' },
    particlePreset: 'mistLeaves',
    particleDensity: 20,
    ambientPreset: 'rainforestWater',
    ambientSound: 'Birds and water',
    animationStyle: 'waterMist',
    voicePreset: 'rainforest_soft',
    textColor: '#EFFFF5',
    subtextColor: '#9ED4B3',
  },
  {
    id: 'assam',
    name: 'Assam',
    subtitle: 'Tea garden fog',
    feeling: 'Fresh air over quiet plantations',
    backgroundImage: sceneImages.assam,
    backgroundGradient: ['#06120AE8', '#102819D2', '#2F5A33B8', '#06120AF2'],
    lightGradient: ['#DAF7BD4F', '#7CCB6238', '#06120AD9'],
    accentColor: '#A3D873',
    secondaryAccentColor: '#5E9A58',
    buttonStyle: { backgroundColor: '#A3D87317', borderColor: '#A3D8734D', textColor: '#F3FFE8' },
    particlePreset: 'fog',
    particleDensity: 14,
    ambientPreset: 'teaGardenWind',
    ambientSound: 'Birds and wind',
    animationStyle: 'grassSway',
    voicePreset: 'fresh_morning',
    textColor: '#F4FFEA',
    subtextColor: '#B8D79E',
  },
  {
    id: 'himalaya',
    name: 'Himalaya',
    subtitle: 'Snow mountain silence',
    feeling: 'Cold air and still meditation',
    backgroundImage: sceneImages.himalaya,
    backgroundGradient: ['#050B14EA', '#102033D6', '#36506CB8', '#050B14F3'],
    lightGradient: ['#DDF6FF59', '#9AC7E233', '#050B14E0'],
    accentColor: '#A7D8F5',
    secondaryAccentColor: '#6EA4C8',
    buttonStyle: { backgroundColor: '#A7D8F514', borderColor: '#A7D8F54A', textColor: '#F0FAFF' },
    particlePreset: 'snow',
    particleDensity: 18,
    ambientPreset: 'mountainWind',
    ambientSound: 'Mountain wind',
    animationStyle: 'movingFog',
    voicePreset: 'cold_silence',
    textColor: '#F2FAFF',
    subtextColor: '#A6C6D9',
  },
  {
    id: 'andaman',
    name: 'Andaman & Nicobar',
    subtitle: 'Ocean island calm',
    feeling: 'Sea light moving slowly',
    backgroundImage: sceneImages.andaman,
    backgroundGradient: ['#021018EA', '#073042D4', '#0C6C7AB8', '#021018F2'],
    lightGradient: ['#B9FCFF55', '#36D7D03A', '#021018D9'],
    accentColor: '#54E1DE',
    secondaryAccentColor: '#39AFC4',
    buttonStyle: { backgroundColor: '#54E1DE17', borderColor: '#54E1DE50', textColor: '#E9FFFF' },
    particlePreset: 'bubbles',
    particleDensity: 22,
    ambientPreset: 'oceanWaves',
    ambientSound: 'Ocean waves',
    animationStyle: 'waterShimmer',
    voicePreset: 'ocean_calm',
    textColor: '#EAFFFF',
    subtextColor: '#94D8D8',
  },
];

export const DEFAULT_THEME_ID = 'kerala';
