// constants/quotes.ts

export interface Quote {
  id: string;
  text: string;
  textHindi?: string;
  attribution: string;
  tradition: string;
  region: string;          // 'rajasthan' | 'himalaya' | 'kerala' | 'assam' | 'andaman' | 'all'
  practiceTag: string;     // 'breathing' | 'meditation' | 'focus' | 'flow' | 'general'
  moodTag: string;         // 'restless' | 'calm' | 'motivated' | 'tired' | 'curious'
}

export const QUOTES: Quote[] = [
  {
    id: 'q1',
    text: 'The forest does not hurry, yet everything is accomplished.',
    textHindi: 'जंगल जल्दी नहीं करता, फिर भी सब कुछ पूरा हो जाता है।',
    attribution: 'Lao Tzu',
    tradition: 'Taoist',
    region: 'assam',
    practiceTag: 'focus',
    moodTag: 'restless',
  },
  {
    id: 'q2',
    text: 'Breath is the bridge which connects life to consciousness.',
    textHindi: 'श्वास वह सेतु है जो जीवन को चेतना से जोड़ती है।',
    attribution: 'Thich Nhat Hanh',
    tradition: 'Buddhist',
    region: 'all',
    practiceTag: 'breathing',
    moodTag: 'calm',
  },
  {
    id: 'q3',
    text: 'Be like the lotus: trust in the light, grow through the dirt, believe in new beginnings.',
    attribution: 'Indian Proverb',
    tradition: 'Hindu',
    region: 'kerala',
    practiceTag: 'meditation',
    moodTag: 'tired',
  },
  {
    id: 'q4',
    text: 'The mind is everything. What you think, you become.',
    textHindi: 'मन ही सब कुछ है। जो तुम सोचते हो, वही बन जाते हो।',
    attribution: 'Gautama Buddha',
    tradition: 'Buddhist',
    region: 'all',
    practiceTag: 'meditation',
    moodTag: 'motivated',
  },
  {
    id: 'q5',
    text: 'In the depth of winter, I finally learned that within me there lay an invincible summer.',
    attribution: 'Albert Camus',
    tradition: 'Philosophy',
    region: 'himalaya',
    practiceTag: 'focus',
    moodTag: 'tired',
  },
  {
    id: 'q6',
    text: 'Yoga is the journey of the self, through the self, to the self.',
    textHindi: 'योग स्वयं की, स्वयं के माध्यम से, स्वयं की ओर यात्रा है।',
    attribution: 'Bhagavad Gita',
    tradition: 'Hindu',
    region: 'all',
    practiceTag: 'meditation',
    moodTag: 'curious',
  },
  {
    id: 'q7',
    text: 'When you realize there is nothing lacking, the whole world belongs to you.',
    attribution: 'Lao Tzu',
    tradition: 'Taoist',
    region: 'andaman',
    practiceTag: 'general',
    moodTag: 'restless',
  },
  {
    id: 'q8',
    text: 'Deep work is the ability to focus without distraction on a cognitively demanding task.',
    attribution: 'Cal Newport',
    tradition: 'Modern',
    region: 'all',
    practiceTag: 'focus',
    moodTag: 'motivated',
  },
  {
    id: 'q9',
    text: 'You have the right to work, but never to the fruit of work.',
    textHindi: 'कर्मण्येवाधिकारस्ते मा फलेषु कदाचन।',
    attribution: 'Bhagavad Gita',
    tradition: 'Hindu',
    region: 'all',
    practiceTag: 'flow',
    moodTag: 'motivated',
  },
  {
    id: 'q10',
    text: 'Smile, breathe, and go slowly.',
    textHindi: 'मुस्कुराओ, साँस लो, और धीरे चलो।',
    attribution: 'Thich Nhat Hanh',
    tradition: 'Buddhist',
    region: 'kerala',
    practiceTag: 'breathing',
    moodTag: 'restless',
  },
  {
    id: 'q11',
    text: 'Nature does not hurry, yet everything is accomplished.',
    attribution: 'Lao Tzu',
    tradition: 'Taoist',
    region: 'assam',
    practiceTag: 'general',
    moodTag: 'tired',
  },
  {
    id: 'q12',
    text: 'Wherever you are, be there totally.',
    textHindi: 'तुम जहाँ भी हो, वहाँ पूरी तरह से रहो।',
    attribution: 'Eckhart Tolle',
    tradition: 'Modern',
    region: 'all',
    practiceTag: 'focus',
    moodTag: 'curious',
  },
  {
    id: 'q13',
    text: 'The quieter you become, the more you can hear.',
    textHindi: 'जितने तुम शांत होगे, उतना ही सुन पाओगे।',
    attribution: 'Ram Dass',
    tradition: 'Modern',
    region: 'himalaya',
    practiceTag: 'meditation',
    moodTag: 'calm',
  },
  {
    id: 'q14',
    text: 'Flow with whatever may happen, and let your mind be free.',
    textHindi: 'जो हो रहा है उसके साथ बहो, और मन को मुक्त रहने दो।',
    attribution: 'Chuang Tzu',
    tradition: 'Taoist',
    region: 'andaman',
    practiceTag: 'flow',
    moodTag: 'curious',
  },
  {
    id: 'q15',
    text: 'To understand the immeasurable, the mind must be extraordinarily quiet, still.',
    attribution: 'Jiddu Krishnamurti',
    tradition: 'Philosophy',
    region: 'all',
    practiceTag: 'meditation',
    moodTag: 'calm',
  },
  {
    id: 'q16',
    text: 'You are the sky. Everything else is just the weather.',
    textHindi: 'तुम आसमान हो। बाकी सब सिर्फ मौसम है।',
    attribution: 'Pema Chödrön',
    tradition: 'Buddhist',
    region: 'rajasthan',
    practiceTag: 'general',
    moodTag: 'restless',
  },
  {
    id: 'q17',
    text: 'Listen to the sound of the river and you will get a trout.',
    attribution: 'Irish Proverb',
    tradition: 'Folk',
    region: 'assam',
    practiceTag: 'focus',
    moodTag: 'motivated',
  },
  {
    id: 'q18',
    text: 'Every breath we take, every step we make, can be filled with peace, joy and serenity.',
    attribution: 'Thich Nhat Hanh',
    tradition: 'Buddhist',
    region: 'all',
    practiceTag: 'breathing',
    moodTag: 'calm',
  },
  {
    id: 'q19',
    text: 'Nothing ever goes away until it has taught us what we need to know.',
    attribution: 'Pema Chödrön',
    tradition: 'Buddhist',
    region: 'himalaya',
    practiceTag: 'meditation',
    moodTag: 'tired',
  },
  {
    id: 'q20',
    text: 'Look past your thoughts, so you may drink the pure nectar of This Moment.',
    attribution: 'Rumi',
    tradition: 'Sufi',
    region: 'rajasthan',
    practiceTag: 'flow',
    moodTag: 'calm',
  },
  {
    id: 'q21',
    text: 'He who conquers himself is the mightiest warrior.',
    textHindi: 'जो स्वयं पर विजय प्राप्त करता है, वही सबसे महान योद्धा है।',
    attribution: 'Confucius',
    tradition: 'Philosophy',
    region: 'all',
    practiceTag: 'focus',
    moodTag: 'motivated',
  },
  {
    id: 'q22',
    text: 'If you are quiet enough, you will hear the flow of the universe.',
    textHindi: 'अगर तुम शांत हो, तो तुम्हें ब्रह्मांड का प्रवाह सुनाई देगा।',
    attribution: 'Rumi',
    tradition: 'Sufi',
    region: 'kerala',
    practiceTag: 'meditation',
    moodTag: 'curious',
  },
  {
    id: 'q23',
    text: 'Feelings come and go like clouds in a windy sky. Conscious breathing is my anchor.',
    attribution: 'Thich Nhat Hanh',
    tradition: 'Buddhist',
    region: 'andaman',
    practiceTag: 'breathing',
    moodTag: 'restless',
  },
  {
    id: 'q24',
    text: 'Do not seek the truth; only cease to cherish opinions.',
    textHindi: 'सत्य की खोज मत करो; केवल अपनी राय को महत्व देना छोड़ दो।',
    attribution: 'Sengcan',
    tradition: 'Zen',
    region: 'himalaya',
    practiceTag: 'meditation',
    moodTag: 'curious',
  },
  {
    id: 'q25',
    text: 'Out of clutter, find simplicity. From discord, find harmony.',
    textHindi: 'अव्यवस्था में सरलता खोजो। असहमति में सद्भाव खोजो।',
    attribution: 'Albert Einstein',
    tradition: 'Science',
    region: 'all',
    practiceTag: 'focus',
    moodTag: 'restless',
  },
  {
    id: 'q26',
    text: 'Quiet the mind, and the soul will speak.',
    textHindi: 'मन को शांत करो, और आत्मा बोलेगी।',
    attribution: 'Ma Jaya Sati Bhagavati',
    tradition: 'Modern',
    region: 'kerala',
    practiceTag: 'meditation',
    moodTag: 'tired',
  },
  {
    id: 'q27',
    text: 'The best way out is always through.',
    attribution: 'Robert Frost',
    tradition: 'Poetry',
    region: 'all',
    practiceTag: 'flow',
    moodTag: 'motivated',
  },
  {
    id: 'q28',
    text: 'Respond; don’t react. Listen; don’t talk. Think; don’t assume.',
    textHindi: 'प्रतिक्रिया न दें; जवाब दें। बोलें नहीं; सुनें।',
    attribution: 'Raji Lukkoor',
    tradition: 'Modern',
    region: 'assam',
    practiceTag: 'focus',
    moodTag: 'calm',
  },
  {
    id: 'q29',
    text: 'Let go of your mind and then be mindful. Close your ears and listen!',
    attribution: 'Rumi',
    tradition: 'Sufi',
    region: 'rajasthan',
    practiceTag: 'meditation',
    moodTag: 'curious',
  },
  {
    id: 'q30',
    text: 'What you seek is seeking you.',
    textHindi: 'जो तुम खोज रहे हो, वह तुम्हें खोज रहा है।',
    attribution: 'Rumi',
    tradition: 'Sufi',
    region: 'all',
    practiceTag: 'flow',
    moodTag: 'motivated',
  },
  {
    id: 'q31',
    text: 'Silence is the sleep that nourishes wisdom.',
    textHindi: 'मौन वह नींद है जो ज्ञान को पोषित करती है।',
    attribution: 'Francis Bacon',
    tradition: 'Philosophy',
    region: 'himalaya',
    practiceTag: 'general',
    moodTag: 'tired',
  },
  {
    id: 'q32',
    text: 'Breathe in deeply to bring your mind home to your body.',
    attribution: 'Thich Nhat Hanh',
    tradition: 'Buddhist',
    region: 'all',
    practiceTag: 'breathing',
    moodTag: 'restless',
  },
  {
    id: 'q33',
    text: 'Everything that has a beginning has an ending. Make your peace with that and all will be well.',
    attribution: 'Jack Kornfield',
    tradition: 'Modern',
    region: 'andaman',
    practiceTag: 'meditation',
    moodTag: 'calm',
  },
  {
    id: 'q34',
    text: 'The present moment is the only moment available to us, and it is the door to all moments.',
    textHindi: 'वर्तमान क्षण ही हमारे लिए उपलब्ध एकमात्र क्षण है।',
    attribution: 'Thich Nhat Hanh',
    tradition: 'Buddhist',
    region: 'all',
    practiceTag: 'general',
    moodTag: 'curious',
  },
  {
    id: 'q35',
    text: 'Concentration is a fine antidote to anxiety.',
    attribution: 'Jack Nicklaus',
    tradition: 'Modern',
    region: 'assam',
    practiceTag: 'focus',
    moodTag: 'restless',
  },
  {
    id: 'q36',
    text: 'In the calm, deep waters of the mind, the wolf waits.',
    attribution: 'F.T. McKinstry',
    tradition: 'Modern',
    region: 'andaman',
    practiceTag: 'flow',
    moodTag: 'tired',
  },
  {
    id: 'q37',
    text: 'Act without expectation.',
    textHindi: 'बिना अपेक्षा के कर्म करो।',
    attribution: 'Lao Tzu',
    tradition: 'Taoist',
    region: 'rajasthan',
    practiceTag: 'flow',
    moodTag: 'motivated',
  },
  {
    id: 'q38',
    text: 'When you catch yourself slipping into a pool of negativity, notice your breath.',
    attribution: 'Lori Deschene',
    tradition: 'Modern',
    region: 'all',
    practiceTag: 'breathing',
    moodTag: 'restless',
  },
  {
    id: 'q39',
    text: 'Nothing is permanent. Don’t stress yourself too much.',
    textHindi: 'कुछ भी स्थायी नहीं है। ज्यादा तनाव मत लो।',
    attribution: 'Indian Proverb',
    tradition: 'Folk',
    region: 'kerala',
    practiceTag: 'general',
    moodTag: 'tired',
  },
  {
    id: 'q40',
    text: 'Mindfulness is a way of befriending ourselves and our experience.',
    attribution: 'Jon Kabat-Zinn',
    tradition: 'Modern',
    region: 'all',
    practiceTag: 'meditation',
    moodTag: 'curious',
  },
  {
    id: 'q41',
    text: 'Set your heart upon your work, but never on its reward.',
    textHindi: 'अपना मन अपने काम पर लगाओ, उसके परिणाम पर कभी नहीं।',
    attribution: 'Bhagavad Gita',
    tradition: 'Hindu',
    region: 'all',
    practiceTag: 'focus',
    moodTag: 'motivated',
  }
];

export function getQuoteForSession(practiceTag: string, theme: string): Quote {
  const matches = QUOTES.filter(
    (q) => (q.practiceTag === practiceTag || q.practiceTag === 'general')
      && (q.region === theme || q.region === 'all'),
  );
  if (matches.length === 0) return QUOTES[0];
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000,
  );
  return matches[dayOfYear % matches.length];
}
